# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import communicate_pb2 as communicate__pb2


class CommunicateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Say = channel.unary_unary(
                '/valet.Communicate/Say',
                request_serializer=communicate__pb2.RequestMessage.SerializeToString,
                response_deserializer=communicate__pb2.ReplyMessage.FromString,
                )


class CommunicateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Say(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunicateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Say': grpc.unary_unary_rpc_method_handler(
                    servicer.Say,
                    request_deserializer=communicate__pb2.RequestMessage.FromString,
                    response_serializer=communicate__pb2.ReplyMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'valet.Communicate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Communicate(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Say(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/valet.Communicate/Say',
            communicate__pb2.RequestMessage.SerializeToString,
            communicate__pb2.ReplyMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
